import os
import re
import json

skills_dir = r"C:\Users\x1 carbon\.gemini\antigravity\skills"
report_path = os.path.join(skills_dir, "audit_report.md")

SECURITY_PATTERNS = {
    "Privilege/Metadata/Locking": [r'\bsudo\b', r'\bchown\b', r'\bchmod\b', r'\bTakeOwnership\b', r'\bicacls\b', r'\bSet-ExecutionPolicy\b', r'\bsetfile\b', r'\battrib\b', r'\bSet-ItemProperty\b', r'\bchflags\b', r'\bchattr\b'],
    "System Changes/Uninstall": [r'msiexec', r'choco uninstall', r'reg delete', r'apt-get purge', r'yum remove'],
    "Mobile Threats": [r'adb shell', r'pm install', r'am start', r'apktool', r'dex2jar', r'keytool', r'xcodebuild', r'codesign', r'fastlane', r'xcrun'],
    "Network Exfiltration": [r'\biwr\b', r'Invoke-WebRequest', r'Invoke-RestMethod', r'\bscp\b', r'\bftp\b', r'\bnc\b', r'\bsocat\b'],
    "Service/Process": [r'Stop-Service', r'taskkill', r'sc\.exe delete', r'kill -9', r'\bpkill\b', r'systemctl disable', r'launchctl unload'],
    "Tubes/Injection": [r'curl.*\|.*bash', r'iwr.*\|.*iex']
}

report = ["# 🛡️ Skills Audit Report\n"]
report.append("*Generated by `@audit-skills` & `@skill-check`*\n")

total_skills = 0
security_issues = {}
structural_issues = {}

for skill_name in sorted(os.listdir(skills_dir)):
    skill_path = os.path.join(skills_dir, skill_name)
    if not os.path.isdir(skill_path) or skill_name.startswith('.'):
        continue
        
    skill_md_path = os.path.join(skill_path, "SKILL.md")
    if not os.path.exists(skill_md_path):
        structural_issues[skill_name] = ["Missing SKILL.md file"]
        continue
        
    total_skills += 1
    
    with open(skill_md_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        
    # --- Skill Check (Structure & Validation) ---
    struct_errors = []
    # Frontmatter check
    if not content.startswith('---'):
        struct_errors.append("Missing YAML frontmatter")
    else:
        if not re.search(r'^name:\s+', content, re.MULTILINE):
            struct_errors.append("Missing `name` in frontmatter")
        if not re.search(r'^description:\s+', content, re.MULTILINE):
            struct_errors.append("Missing `description` in frontmatter")
            
    # Body check
    if "## When to Use" not in content and "When to use" not in content and "when to use" not in content.lower():
         struct_errors.append("Missing 'When to Use' section")
         
    if struct_errors:
        structural_issues[skill_name] = struct_errors
        
    # --- Security Audit ---
    sec_errors = []
    for category, patterns in SECURITY_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, content, re.IGNORECASE):
                # We skip certain common innocent uses, but log for review
                sec_errors.append(f"Contains `{pattern}` ({category})")
                
    # remove duplicate sec errors
    sec_errors = list(set(sec_errors))
    if sec_errors:
        security_issues[skill_name] = sec_errors

# Format Report
report.append(f"**Total Skills Scanned:** {total_skills}\n")

report.append("## 🚨 Security Flags (`@audit-skills`)")
if security_issues:
    report.append(f"Found potential security patterns in {len(security_issues)} skills (Note: Many may be false positives for legitimate tools):")
    for skill, issues in list(security_issues.items())[:50]: # limit to 50
        report.append(f"- **{skill}**: {', '.join(issues)}")
    if len(security_issues) > 50:
        report.append("- ... *and more*")
else:
    report.append("✅ No critical security patterns detected.")

report.append("\n## ⚠️ Structural Issues (`@skill-check`)")
if structural_issues:
    report.append(f"Found structural/formatting issues in {len(structural_issues)} skills:")
    # Group by error types
    for skill, issues in list(structural_issues.items())[:50]: # limit to 50
        report.append(f"- **{skill}**: {', '.join(issues)}")
    if len(structural_issues) > 50:
        report.append("- ... *and more*")
else:
    report.append("✅ All skills pass basic structural checks.")
    
with open(report_path, 'w', encoding='utf-8') as f:
    f.write("\n".join(report))

print(f"Audit complete. Report generated at {report_path}")
